### ISSUE TITLE
Triagr link under "Get involved" 404s

### ISSUE THREAD

**Issue by edmorley** [DouglasSherk/Firefox-OS-Dogfooding#10]
1. Go to http://foxfooding.github.io/
2. Open "Get Involved" menu
3. Choose "Triagr"

-> http://foxfooding.github.io/triagr

...which 404s.

**Comment by gaby2300** [comment]
I have the same issue.

**Comment by edmorley** [comment]
Closing this out to de-clutter my GitHub open issues dashboard since this repo is deprecated.
